--  17) DISPLAY ALL THE EMPLOYEE WHO ARE ‘SALESMAN’S HAVING ‘E’ AS THE LAST BUT ONE 
-- CHARACTER  IN ENAME BUT SALARY HAVING EXACTLY 4 CHARACTER 

SELECT ename FROM scott_db.emp WHERE job = 'SALESMAN' AND ename LIKE '%E_' AND sal BETWEEN 1000 AND 9999;